version: '3'
services:
  web:
    build: .
    environment:
      - DEBUG=xcarpaccio:server
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
